name: ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dotnet: 3.1.x
            framework: netcoreapp3.1
          - dotnet: 5.0.x
            framework: net5.0

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build
      run: dotnet build -f "${{ matrix.framework }}"
    - name: Test
      run: dotnet test --no-build --verbosity normal -f "${{ matrix.framework }}"
